INC = -I lib/

SRC =	list_init.cpp \
		list_print.cpp \
		list_add_end.cpp \
		list_add_start.cpp \
		list_add_after.cpp \
		list_is_empty.cpp  \
		list_new_sort.cpp \
		list_count.cpp \
		list_del.cpp \
		list_add_node.cpp \
		list_node_del.cpp

all:
	g++ main.cpp $(SRC) $(INC)
