INC = -I lib/

SRC =	list_init.cpp \
		list_print.cpp \
		add_end.cpp \
		add_start.cpp \
		add_after.cpp \
		is_empty.cpp  \
		list_new_sort.cpp \
		list_count.cpp \
		node_del.cpp \
		add_node.cpp \
		list_del.cpp

all:
	g++ main.cpp $(SRC) $(INC)
